CREATE TABLE goalies (
    id BIGINT NOT NULL,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    headshot VARCHAR(255),
    sweater_number INTEGER,
    team_abbrev VARCHAR(255),
    team_name VARCHAR(255),
    team_logo_light VARCHAR(255),
    team_logo_dark VARCHAR(255),
    wins INTEGER,
    losses INTEGER,
    overtime_losses INTEGER,
    games_played INTEGER,
    goals_against_avg DOUBLE PRECISION,
    save_pctg DOUBLE PRECISION,
    PRIMARY KEY (id)
);

CREATE TABLE shot_location_summary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    goalie_id BIGINT,
    location_code VARCHAR(255),
    goals_against INTEGER,
    goals_against_percentile DOUBLE PRECISION,
    goals_against_league_avg DOUBLE PRECISION,
    saves INTEGER,
    saves_percentile DOUBLE PRECISION,
    saves_league_avg DOUBLE PRECISION,
    save_pctg DOUBLE PRECISION,
    save_pctg_percentile DOUBLE PRECISION,
    save_pctg_league_avg DOUBLE PRECISION,
    PRIMARY KEY (id),
    CONSTRAINT fk_shot_location_summary_goalie
        FOREIGN KEY (goalie_id) REFERENCES goalies (id)
);

CREATE TABLE shot_location_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    goalie_id BIGINT,
    area VARCHAR(255),
    saves INTEGER,
    saves_percentile DOUBLE PRECISION,
    save_pctg DOUBLE PRECISION,
    save_pctg_percentile DOUBLE PRECISION,
    PRIMARY KEY (id),
    CONSTRAINT fk_shot_location_detail_goalie
        FOREIGN KEY (goalie_id) REFERENCES goalies (id)
);

CREATE INDEX idx_shot_location_summary_goalie_id ON shot_location_summary (goalie_id);
CREATE INDEX idx_shot_location_detail_goalie_id ON shot_location_detail (goalie_id);
