ALTER TABLE goalies ADD COLUMN height_cm INTEGER;
ALTER TABLE goalies ADD COLUMN weight_kg INTEGER;
ALTER TABLE goalies ADD COLUMN catches VARCHAR(1);
ALTER TABLE goalies ADD COLUMN birth_date DATE;
ALTER TABLE goalies ADD COLUMN birth_city VARCHAR(120);
ALTER TABLE goalies ADD COLUMN birth_state_province VARCHAR(120);
ALTER TABLE goalies ADD COLUMN birth_country VARCHAR(3);
ALTER TABLE goalies ADD COLUMN nationality VARCHAR(3);
ALTER TABLE goalies ADD COLUMN position_code VARCHAR(4);
ALTER TABLE goalies ADD COLUMN profile_updated_at TIMESTAMP WITH TIME ZONE;

CREATE TABLE seasons (
    id VARCHAR(8) NOT NULL,
    display_name VARCHAR(9) NOT NULL,
    starts_on DATE NOT NULL,
    ends_on DATE NOT NULL,
    is_current BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id),
    CONSTRAINT ck_seasons_date_range CHECK (ends_on >= starts_on)
);

CREATE TABLE teams (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nhl_franchise_id INTEGER,
    abbreviation VARCHAR(3) NOT NULL,
    common_name VARCHAR(120) NOT NULL,
    logo_light_url VARCHAR(500),
    logo_dark_url VARCHAR(500),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (id),
    CONSTRAINT uq_teams_abbreviation UNIQUE (abbreviation),
    CONSTRAINT uq_teams_nhl_franchise_id UNIQUE (nhl_franchise_id)
);

CREATE TABLE goalie_team_stints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    goalie_id BIGINT NOT NULL,
    season_id VARCHAR(8) NOT NULL,
    team_id INTEGER NOT NULL,
    stint_number SMALLINT NOT NULL DEFAULT 1,
    sweater_number INTEGER,
    started_on DATE,
    ended_on DATE,
    source_name VARCHAR(80) NOT NULL,
    source_updated_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (id),
    CONSTRAINT fk_goalie_team_stints_goalie FOREIGN KEY (goalie_id) REFERENCES goalies (id),
    CONSTRAINT fk_goalie_team_stints_season FOREIGN KEY (season_id) REFERENCES seasons (id),
    CONSTRAINT fk_goalie_team_stints_team FOREIGN KEY (team_id) REFERENCES teams (id),
    CONSTRAINT uq_goalie_team_stints UNIQUE (goalie_id, season_id, team_id, stint_number),
    CONSTRAINT ck_goalie_team_stints_date_range CHECK (ended_on IS NULL OR started_on IS NULL OR ended_on >= started_on)
);

CREATE TABLE goalie_season_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    team_stint_id BIGINT NOT NULL,
    games_played INTEGER NOT NULL DEFAULT 0,
    games_started INTEGER,
    wins INTEGER NOT NULL DEFAULT 0,
    losses INTEGER NOT NULL DEFAULT 0,
    overtime_losses INTEGER NOT NULL DEFAULT 0,
    shots_against INTEGER,
    saves INTEGER,
    goals_against INTEGER,
    goals_against_avg DOUBLE PRECISION,
    save_pctg DOUBLE PRECISION,
    shutouts INTEGER,
    time_on_ice_seconds INTEGER,
    source_name VARCHAR(80) NOT NULL,
    source_updated_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (id),
    CONSTRAINT fk_goalie_season_stats_stint FOREIGN KEY (team_stint_id) REFERENCES goalie_team_stints (id),
    CONSTRAINT uq_goalie_season_stats_stint UNIQUE (team_stint_id),
    CONSTRAINT ck_goalie_season_stats_nonnegative CHECK (
        games_played >= 0 AND wins >= 0 AND losses >= 0 AND overtime_losses >= 0
    )
);

CREATE TABLE games (
    id BIGINT NOT NULL,
    season_id VARCHAR(8) NOT NULL,
    game_date DATE NOT NULL,
    game_type SMALLINT NOT NULL,
    home_team_id INTEGER NOT NULL,
    away_team_id INTEGER NOT NULL,
    home_score INTEGER,
    away_score INTEGER,
    game_state VARCHAR(32),
    source_name VARCHAR(80) NOT NULL,
    source_updated_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (id),
    CONSTRAINT fk_games_season FOREIGN KEY (season_id) REFERENCES seasons (id),
    CONSTRAINT fk_games_home_team FOREIGN KEY (home_team_id) REFERENCES teams (id),
    CONSTRAINT fk_games_away_team FOREIGN KEY (away_team_id) REFERENCES teams (id),
    CONSTRAINT ck_games_distinct_teams CHECK (home_team_id <> away_team_id)
);

CREATE TABLE goalie_game_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    game_id BIGINT NOT NULL,
    goalie_id BIGINT NOT NULL,
    team_id INTEGER NOT NULL,
    is_starter BOOLEAN,
    decision VARCHAR(3),
    time_on_ice_seconds INTEGER,
    shots_against INTEGER,
    saves INTEGER,
    goals_against INTEGER,
    save_pctg DOUBLE PRECISION,
    source_name VARCHAR(80) NOT NULL,
    source_updated_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (id),
    CONSTRAINT fk_goalie_game_stats_game FOREIGN KEY (game_id) REFERENCES games (id),
    CONSTRAINT fk_goalie_game_stats_goalie FOREIGN KEY (goalie_id) REFERENCES goalies (id),
    CONSTRAINT fk_goalie_game_stats_team FOREIGN KEY (team_id) REFERENCES teams (id),
    CONSTRAINT uq_goalie_game_stats_goalie_game UNIQUE (game_id, goalie_id),
    CONSTRAINT ck_goalie_game_stats_nonnegative CHECK (
        shots_against IS NULL OR shots_against >= 0
    )
);

CREATE TABLE shot_zone_aggregates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    goalie_id BIGINT NOT NULL,
    season_id VARCHAR(8) NOT NULL,
    game_id BIGINT,
    team_id INTEGER,
    scope VARCHAR(12) NOT NULL,
    zone_code VARCHAR(64) NOT NULL,
    shots_against INTEGER NOT NULL DEFAULT 0,
    saves INTEGER NOT NULL DEFAULT 0,
    goals_against INTEGER NOT NULL DEFAULT 0,
    save_pctg DOUBLE PRECISION,
    source_name VARCHAR(80) NOT NULL,
    source_updated_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (id),
    CONSTRAINT fk_shot_zone_aggregates_goalie FOREIGN KEY (goalie_id) REFERENCES goalies (id),
    CONSTRAINT fk_shot_zone_aggregates_season FOREIGN KEY (season_id) REFERENCES seasons (id),
    CONSTRAINT fk_shot_zone_aggregates_game FOREIGN KEY (game_id) REFERENCES games (id),
    CONSTRAINT fk_shot_zone_aggregates_team FOREIGN KEY (team_id) REFERENCES teams (id),
    CONSTRAINT ck_shot_zone_aggregates_scope CHECK (
        (scope = 'SEASON' AND game_id IS NULL) OR (scope = 'GAME' AND game_id IS NOT NULL)
    ),
    CONSTRAINT ck_shot_zone_aggregates_counts CHECK (
        shots_against >= 0 AND saves >= 0 AND goals_against >= 0
    ),
    CONSTRAINT uq_shot_zone_aggregates UNIQUE (goalie_id, season_id, game_id, team_id, scope, zone_code)
);

CREATE TABLE data_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(80) NOT NULL,
    base_url VARCHAR(500) NOT NULL,
    attribution VARCHAR(500),
    PRIMARY KEY (id),
    CONSTRAINT uq_data_sources_name UNIQUE (name)
);

CREATE TABLE import_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_id BIGINT,
    import_type VARCHAR(40) NOT NULL,
    season_id VARCHAR(8),
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    status VARCHAR(16) NOT NULL,
    records_read INTEGER NOT NULL DEFAULT 0,
    records_written INTEGER NOT NULL DEFAULT 0,
    error_detail TEXT,
    PRIMARY KEY (id),
    CONSTRAINT fk_import_runs_source FOREIGN KEY (source_id) REFERENCES data_sources (id),
    CONSTRAINT fk_import_runs_season FOREIGN KEY (season_id) REFERENCES seasons (id),
    CONSTRAINT ck_import_runs_status CHECK (status IN ('RUNNING', 'SUCCEEDED', 'FAILED', 'PARTIAL'))
);

CREATE TABLE model_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    metric_name VARCHAR(120) NOT NULL,
    version VARCHAR(64) NOT NULL,
    methodology_url VARCHAR(500),
    description TEXT,
    active_from TIMESTAMP WITH TIME ZONE NOT NULL,
    retired_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (id),
    CONSTRAINT uq_model_versions_metric_version UNIQUE (metric_name, version)
);

CREATE INDEX idx_goalie_team_stints_season_goalie ON goalie_team_stints (season_id, goalie_id);
CREATE INDEX idx_goalie_season_stats_stint ON goalie_season_stats (team_stint_id);
CREATE INDEX idx_games_season_date ON games (season_id, game_date);
CREATE INDEX idx_goalie_game_stats_goalie_game ON goalie_game_stats (goalie_id, game_id);
CREATE INDEX idx_shot_zone_aggregates_goalie_season ON shot_zone_aggregates (goalie_id, season_id);
CREATE INDEX idx_import_runs_status_started ON import_runs (status, started_at);

INSERT INTO seasons (id, display_name, starts_on, ends_on, is_current)
VALUES ('20262027', '2026-27', DATE '2026-10-01', DATE '2027-06-30', TRUE);

INSERT INTO data_sources (name, base_url, attribution)
VALUES ('NHL API', 'https://api-web.nhle.com/', 'NHL public API data');

INSERT INTO teams (abbreviation, common_name, logo_light_url, logo_dark_url)
SELECT DISTINCT team_abbrev, team_name, team_logo_light, team_logo_dark
FROM goalies
WHERE team_abbrev IS NOT NULL AND TRIM(team_abbrev) <> '';

INSERT INTO goalie_team_stints (goalie_id, season_id, team_id, sweater_number, source_name)
SELECT g.id, '20262027', t.id, g.sweater_number, 'legacy-hibernate'
FROM goalies g
JOIN teams t ON t.abbreviation = g.team_abbrev
WHERE g.team_abbrev IS NOT NULL AND TRIM(g.team_abbrev) <> '';

INSERT INTO goalie_season_stats (
    team_stint_id, games_played, wins, losses, overtime_losses, goals_against_avg, save_pctg, source_name
)
SELECT s.id, COALESCE(g.games_played, 0), COALESCE(g.wins, 0), COALESCE(g.losses, 0), COALESCE(g.overtime_losses, 0),
       g.goals_against_avg, g.save_pctg, 'legacy-hibernate'
FROM goalies g
JOIN goalie_team_stints s ON s.goalie_id = g.id AND s.season_id = '20262027';
