CREATE TABLE shot_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    game_id BIGINT NOT NULL,
    season_id VARCHAR(8) NOT NULL,
    nhl_event_id INTEGER NOT NULL,
    goalie_id BIGINT NOT NULL,
    defending_team_id INTEGER NOT NULL,
    x_coordinate INTEGER NOT NULL,
    y_coordinate INTEGER NOT NULL,
    outcome VARCHAR(8) NOT NULL,
    source_name VARCHAR(80) NOT NULL,
    source_updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_shot_events_game FOREIGN KEY (game_id) REFERENCES games (id),
    CONSTRAINT fk_shot_events_season FOREIGN KEY (season_id) REFERENCES seasons (id),
    CONSTRAINT fk_shot_events_goalie FOREIGN KEY (goalie_id) REFERENCES goalies (id),
    CONSTRAINT fk_shot_events_team FOREIGN KEY (defending_team_id) REFERENCES teams (id),
    CONSTRAINT ck_shot_events_outcome CHECK (outcome IN ('SAVE', 'GOAL')),
    CONSTRAINT uq_shot_events_game_event UNIQUE (game_id, nhl_event_id)
);

CREATE INDEX idx_shot_events_goalie_season ON shot_events (goalie_id, season_id);
CREATE INDEX idx_shot_events_game ON shot_events (game_id);
